os: linux
dist: xenial
language: node_js
node_js:
- 14

before_install:
- npm config set //npm.greensock.com/:_authToken=$GSAP_TOKEN
- npm config set @gsap:registry=https://npm.greensock.com
install:
- yarn add gsap@npm:@gsap/shockingly
- yarn add puppeteer
- yarn install
cache:
  yarn: true
script:
- gatsby build
deploy:
- provider: script
  script: rsync -r --delete-after $TRAVIS_BUILD_DIR/public/ root@167.86.92.134:/root/hoezithet/dev_public
  edge: true
  on:
    branch: develop
- provider: script
  script: node scripts/create_lesson_pdfs_pngs.js --host=dev.hoezithet.nu --cwd=$TRAVIS_BUILD_DIR
  on:
    branch: develop
- provider: script
  script: rsync -r --delete-after $TRAVIS_BUILD_DIR/public/ root@167.86.92.134:/root/hoezithet/dev_public
  edge: true
  on:
    branch: develop

- provider: script
  script: rsync -r --delete-after $TRAVIS_BUILD_DIR/public/ root@167.86.92.134:/root/hoezithet/public
  edge: true
  on:
    branch: master
- provider: script
  script: node scripts/create_lesson_pdfs_pngs.js --host=hoezithet.nu --cwd=$TRAVIS_BUILD_DIR
  on:
    branch: master
- provider: script
  script: rsync -r --delete-after $TRAVIS_BUILD_DIR/public/ root@167.86.92.134:/root/hoezithet/public
  edge: true
  on:
    branch: master

addons:
  ssh_known_hosts: 167.86.92.134
branches:
  only:
  - master
  - develop
notifications:
  slack: hoezithet:XvtMGEvLV8a37LQTUioGFVoa
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
env:
  global:
  - secure: EV4OJQAseQ5qUwa4OQXTIQp4XXVl8IdzeXkO27gvGwdIY6VVZjS0+biwopDXKBiRyNUJdIYbW/2Tt3AcND+zMgXiPHoXudCNgibDIiKZ001+3acPDp2S71HbugaRM3J+MBjerUhw7c2WRiE3qpTjRvHilcEi3s7I8KcI56w63wCpvYpCufjqG9slAaFC+DpZ28sFlKBRlaiP+3eqS8y7Rgsv+366pYn6jkWfsau2bRaTGa4dLwzEfcDiGSe/7DHRYkxb1iDBuqAzlIdcJveyIIBWidcmbRbQ/neTU63HYgfHcw9WPmXACQyy7i+FyCm9I7Q8DXtV9rydWDfUlTGyWzcxFXFnvcLX8Tbx2N1fPYQWE1PV6B38WT20C3yfIxCxTs3wEx5xeqvgnqGg9AY057CypGf5DqriTkckoJrx8D2NgoLJCsCeu1amyuBvCVfP4MgPxUHSAxUGvBTEYf8ok539IBu/b77kWIRufVaNZTUxE0WV208R/mBCA28+lJbdBn0CKMQLTap9Go275LsYtvCZiQp1g+NuYsEySI5AUGrw6rcHyq4NYFkj1DAdmBbjRHTdCxeoiKse1jbnaYTTcKUZgreOnhi0JO00UPyETHoUrvyTfPYLUH8HOEFkXjxLVpSzxpgnGjeKHOf954Kiqvz1UdHoBdNapyTkK5MQPM8=
  - secure: b9G00OJDVXRn1y+vKHeoTDSWw7/QhQeasKs7ufwTVgRQSdD2so4FIBH5gPYv8TYLqOKoMzpSKfWZjqNL0c5pAI256TW3/VZCCO0q84jCrSGT1cwdMyxJJodmLNiTJg74TXgoKbltJUxT5yddwxxfy6fGB4SvHTgwInTjSkqRoGKknnWR7AE40JwehXvwzwqfMHkXRaTEPMgmpW7P6iIfl5KBxQmmLFSRL2UF+uxG4KoWjfLwaKQbfdl8i1JuZaoEBijG/K7PTknuBLCOV4JR/oAJVxc0Hu3yt/VQj6bs2r6+Bq5IUxUUhgvgj2fY5mJL2W3LatTkPJbVqNIMmeEDp9S38sYcTx5ZuMjNsh04T62zAsFDCGAjOMtB3PHQ7cHGpviS6PTBR4WcbuanBrjLfz88pA33NdSeXCwPA+jGlmwIQ4mkTQJtL/GmA/QNhGlJ548K4PKxuISQlZyKi8WVkxx3earvdZl1zbwO+QJghL8PultESEDQkCXG+Qzj0sCEZkdm9lEpr5ZWNSJE4FIxNW7MSypF9LxTeqNtbQMjmjtLId2J1bMFqt7wzIsxYaLObaXz2+xZeSBJUH2ZUxOprF5A8jSutqmB2Cnolrxc1nZaEjs9SKp+mmvlVCtqHza8d6eBXcHKrT+RLhxvDtyWYNcsjdcWuJVZyYorfwGRpiA=
