os: linux
dist: xenial
language: node_js
node_js:
  - 14
cache:
  directories:
  - node_modules
install:
- npm install
script:
- gatsby build
deploy:
- provider: script
  script: rsync -r --delete public root@167.86.92.134:/root/hoezithet/dev_public
  on:
    branch: develop
addons:
  ssh_known_hosts: 167.86.92.134
branches:
  only:
  - master
  - develop
notifications:
  slack: $SLACK_KEY
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
secure: "YGL2JutDOoZRNbPcr1iyW/9wm56hYck3bALTzaUdobDSKHH384h6GeTP+5EdcoEYwceIs/Wi77HL9WsieapCmBqan7DU47pgZMKf6zZg6ug7Q+aHctCLGFVm6SgWJSCF/+YSVSMeKcFJTlC4H6wm2bNxZfIi/lIvIIZ1yxtLvNt51YXcbDXL279Ly2x+uUtuFW4zhK2mt0UpiVxQV8JInNPKZyGs9LZiMSSGM89J1vULmrNtS3BSacGtI7UyAl5OzpD8J5NfJkJjgvV9weAwAJtULdB8rHEFBT8bIPjzhWCYHZhrSWFhO44RT57ZEQxCyLEsdL4JSPi4D59gV4B6u3FekUjgCR4v8nc1e1jXWku6dyhoVre6JPe/miYFsFrlCVrlthMdpB9idBlbs+pwkMkH3vqXORIeWkAYxEll/3simmrM+eBzpjgE5gSgY8d1r91xVmI7WJHY1oTjroCG3ptSkjBhR7dCKXHgm0wsJLHbRxLYZ3TgmPJSFWb69oLop6HzZBWsJzjofSislB/DAD8yGuG4cPiC9QPAc/eXX1b/v0txZU9JJOkRD18Aw2SsHWAwjFv1+nrIeq/8gkWEomStHXJ1CCQwxcjQv7QWx8ly/GmWSzjuODtJocfJY98jR9dekF5y+Le8WeY6Ykg12oEMYYIDIuM3fNCJ13gZRI0="