module.exports = {
    // Add any KaTeX options from https://github.com/KaTeX/KaTeX/blob/master/docs/options.md here
    macros: {
        "\\deg": "^{\\circ}",
        "\\norm": "\\lVert#1\\rVert",
        "\\breq": "\\stackrel{\\text{BR}}{=}",
        "\\darkred": "{\\color{e7040f}{#1}}",
        "\\red": "{\\color{ff4136}{#1}}",
        "\\lightred": "{\\color{ff725c}{#1}}",
        "\\orange": "{\\color{ff6300}{#1}}",
        "\\gold": "{\\color{ffb700}{#1}}",
        "\\yellow": "{\\color{ffde37}{#1}}",
        "\\lightyellow": "{\\color{fbf1a9}{#1}}",
        "\\purple": "{\\color{5e2ca5}{#1}}",
        "\\lightpurple": "{\\color{a463f2}{#1}}",
        "\\darkpink": "{\\color{d5008f}{#1}}",
        "\\hotpink": "{\\color{ff41b4}{#1}}",
        "\\pink": "{\\color{ff80cc}{#1}}",
        "\\lightpink": "{\\color{ffa3d7}{#1}}",
        "\\darkgreen": "{\\color{137752}{#1}}",
        "\\green": "{\\color{19a974}{#1}}",
        "\\lightgreen": "{\\color{9eebcf}{#1}}",
        "\\navy": "{\\color{001b44}{#1}}",
        "\\darkblue": "{\\color{00449e}{#1}}",
        "\\blue": "{\\color{357edd}{#1}}",
        "\\lightblue": "{\\color{96ccff}{#1}}",
        "\\lightestblue": "{\\color{cdecff}{#1}}",
        "\\washedblue": "{\\color{f6fffe}{#1}}",
        "\\washedgreen": "{\\color{e8fdf5}{#1}}",
        "\\washedyellow": "{\\color{fffceb}{#1}}",
        "\\washedred": "{\\color{ffdfdf}{#1}}",
        "\\grey": "{\\color{d3d3d3}{#1}}",
        "\\gray": "{\\color{d3d3d3}{#1}}",

        "\\dblue": "{\\color{00449e}{#1}}",
        "\\black": "{\\color{000000}{#1}}",
        "\\pos": "{\\color{19a974}{#1}}",
        "\\neg": "{\\color{e7040f}{#1}}",
        "\\neut": "{\\color{357edd}{#1}}",
        "\\atten": "{\\color{ff6300}{#1}}",
        "\\link": "{\\color{357edd}{#1}}",

        "\\clra": "{\\color{ff6300}{#1}}",
        "\\clrb": "{\\color{00449e}{#1}}",
        "\\clrc": "{\\color{d5008f}{#1}}",
        "\\clrd": "{\\color{e7040f}{#1}}",
        "\\clre": "{\\color{19a974}{#1}}",

        "\\mute": "{\\color{d3d3d3}{#1}}",

        "\\si": "\\text",

        "\\exVar": "\\htmlClass{exVar #1}{}",

        "\\moveFrom": "\\htmlClass{moveFrom animLabel#2}{#1}",
        "\\moveTo": "\\htmlClass{moveTo animLabel#2}{#1}",
        "\\morphFrom": "\\htmlClass{morphFrom animLabel#2}{#1}",
        "\\morphTo": "\\htmlClass{morphTo animLabel#2}{#1}",

        "\\RR": "\\mathbb{R}",
        "\\Udarr": "\\Updownarrow",
        "\\Lrarr": "\\Leftrightarrow",
        "\\euro": "\\text{€}",
    },
    colorIsTextColor: true,
    strict: "ignore",
    trust: true,
}
